# Etapa 1: Construcción del frontend
FROM node:18-alpine AS build

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código del proyecto
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine

# Copiar los archivos generados del build al servidor Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exponer el puerto donde correrá la app
EXPOSE 80

# Iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
